[package]
name = "chip-8"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.15.3", features = [] }
image = "0.25.5"
iyes_perf_ui = "0.4.0"
rand = "0.9.0"
rand_pcg = "0.9.0"
rayon = "1.10.0"

[features]
print = []
